apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackerauth
spec:
  selector:
    matchLabels:
      app: trackerauth
  template:
    metadata:
      labels:
        app: trackerauth
    spec:
      containers:
      - name: trackerauth
        image: sakthisaran/tracker_auth:BUILDNUMBER
        env:
        - name: AUTH_JWT_SIGNATURE_SECRET
          valueFrom:
            secretKeyRef:
              name: secretpasswords
              key: AUTH_JWT_SIGNATURE_SECRET

        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: trackerauthservice
spec:
  type: ClusterIP
  selector:
    app: trackerauth
  ports:
  - port: 80
    targetPort: 80

